/**
 * Fastify plugin: GET /api/openapi.json
 *
 * Public, unauthenticated route that serves the OpenAPI 3.0 specification
 * generated by @fastify/swagger. No session required — the spec is public
 * information and is consumed by client tooling and documentation generators.
 *
 * Mounted from `buildApp()` with prefix `/api`, so the effective path is
 * `/api/openapi.json` even though this file declares only `/openapi.json`.
 *
 * API-013.
 */

import type { FastifyInstance, FastifyPluginAsync } from 'fastify';

const openapiRoute: FastifyPluginAsync = async (fastify: FastifyInstance) => {
  fastify.get('/openapi.json', async (_req, reply) => {
    return reply.send(fastify.swagger());
  });
};

export default openapiRoute;
